apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi